title: My Jekyll Page
author: ansnotant
email: ansnotant@163.com
description: > # this means to ignore newlines until "baseurl:"
  If you come here, you know too much for the world

# social links
twitter_username: I have no twitter, because it's blocked
github_username:  ansnotant

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
